language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "hhvm"

matrix:
  fast_finish: true

services:
    - redis-server
    - memcached

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./.travis.cache.sh; fi;'
    - composer self-update
    - composer install --dev --prefer-source --no-interaction

script:
    - php vendor/bin/phpunit
