language: php
php:
  - "7.0"
  - "5.6"

matrix:
  fast_finish: true

sudo: false

before_install:
    - pip install --user codecov

before_script:
    - composer self-update
    - composer install --dev --prefer-source --no-interaction

script:
    - php vendor/bin/phpunit

after_succes:
    - codecov